spring:
  application:
    name: any-profile-service
  datasource:
    url: jdbc:hsqldb:mem:testdb
    username: sa
    password:
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true